#!/bin/bash

set -e
set -u

ip="${1:-localhost}"
export url="osc.udp://[${ip}]:7777"

txt2pbm()
{
	local pointwidth=5
	local pointsize=9
	local style=r
	local width=112
	local height=16
	local rotation=0

	convert \
		-size ${width}x${height} \
		-font "/usr/share/fonts/misc/Tamsyn${pointwidth}x${pointsize}${style}.pcf" \
		-pointsize ${pointsize} \
		-gravity center \
		-interline-spacing '-2' \
		caption:"${1:-MonoBus}" \
		-rotate ${rotation} \
		pbm:
}

export -f txt2pbm

render()
{
	txt2pbm "$( fortune -n 40 -s )"
}

export -f render

animate()
{
	render | monobusc -U ${url}
}

export -f animate

exec watch -n 20 animate
