.TH MONOBUSC "1" "Oct 03, 2019"

.SH NAME
monobusc \- an OSC to Lawo MonoBus bridge client application

.SH SYNOPSIS
.B monobusc
[\fIOPTIONS\fR] \fIFILE.PBM\fR

.SH DESCRIPTION
\fBmonobusc\fP sends bitmap data via OSC to the monobus daemon application.

.SH OPTIONS
.HP
\fB\-v\fR
.IP
Print version and license information

.HP
\fB\-h\fR
.IP
Print usage information

.HP
\fB\-d\fR
.IP
Enable debug logging

.HP
\fB\-U\fR URL
.IP
OSC URI (osc.udp://:6666)

.SH LICENSE
Artistic License 2.0.

.SH AUTHOR
Hanspeter Portner (dev@open-music-kontrollers.ch).
