.TH MONOBUSC "1" "Oct 03, 2019"

.SH NAME
monobusc \- an OSC to Lawo MonoBus bridge client application

.SH SYNOPSIS
.B monobusc
[\fIOPTIONS\fR]

.SH DESCRIPTION
\fBmonobusc\fP sends bitmap data via OSC to the monobus daemon application.
Reads from stdin by default.

.SH OPTIONS
.HP
\fB\-v\fR
.IP
Print version and license information

.HP
\fB\-h\fR
.IP
Print usage information

.HP
\fB\-d\fR
.IP
Enable debug logging

.HP
\fB\-P\fR PRIO
.IP
Set priority of message (0)

.HP
\fB\-X\fR X_OFFSET
.IP
Set x-offset of bitmap (0)

.HP
\fB\-Y\fR Y_OFFSET
.IP
Set y-offset of bitmap (0)

.HP
\fB\-U\fR URL
.IP
OSC URI (osc.udp://localhost:7777)

.HP
\fB\-I\fR FILE
.IP
Bitmap file in PBM format (-)

.SH LICENSE
Artistic License 2.0.

.SH AUTHOR
Hanspeter Portner (dev@open-music-kontrollers.ch).
