#!/bin/bash

set -e
set -u

txt2pbm()
{
	local pointsize=18
	local style=b
	local width=112
	local height=16
	local rotation=90

	convert \
		-size ${width}x${height} \
		-font "/usr/share/fonts/misc/ter-x${pointsize}${style}.pcf.gz" \
		-pointsize ${pointsize} \
		-gravity East \
		caption:"${1:-MonoBus}" \
		-rotate ${rotation} \
		pbm:
}

export -f txt2pbm

render()
{
	local unixtime

	unixtime=$( date +%s )

	txt2pbm "$( printf 0x%08x "${unixtime}" )"
}

export -f render

animate()
{
	render | monobusc
}

export -f animate

exec watch -n 1 animate
